import Syllabary from "./interfaces/Syllabary";

const syllabary: Syllabary = [
  [
    {hideIfRomanji: true},
    {
      romanji: "a",
      title: true,
    },
    {
      romanji: "i",
      title: true,
    },
    {
      romanji: "u",
      title: true,
    },
    {
      romanji: "e",
      title: true,
    },
    {
      romanji: "o",
      title: true,
    },
    {
      romanji: "ya",
      title: true,
      digraph: true,
    },
    {
      romanji: "yu",
      title: true,
      digraph: true,
    },
    {
      romanji: "yo",
      title: true,
      digraph: true,
    },
  ],
  [
    {},
    {
      romanji: "a",
      hiragana: "あ",
      katakana: "ア",
      pronunciation: "[a]",
      similarHiragana: ["o"],
      similarKatakana: ["ma", "ya"],
      frequency: 0.0543063900914,
      strokes: [1.9, 7.05],
      base: ["a"],
    },
    {
      romanji: "i",
      hiragana: "い",
      katakana: "イ",
      pronunciation: "[i]",
      similarHiragana: ["ri"],
      frequency: 0.2770247695934,
      strokes: [1.9, 5.6875],
      base: ["i"],
    },
    {
      romanji: "u",
      hiragana: "う",
      katakana: "ウ",
      pronunciation: "[u͍]",
      frequency: 0.277753235527,
      strokes: [1.9, 4.325],
      base: ["u"],
      similarKatakana: ["wa", "vu"],
    },
    {
      romanji: "e",
      hiragana: "え",
      katakana: "エ",
      pronunciation: "[e]",
      frequency: 0.0476143607298,
      strokes: [1.9, 2.9625],
      base: ["e"],
    },
    {
      romanji: "o",
      hiragana: "お",
      katakana: "オ",
      pronunciation: "[o]",
      similarHiragana: ["a"],
      similarKatakana: ["ho"],
      frequency: 0.0602449838196,
      strokes: [1.9, 1.6],
      base: ["o"],
    },
    {
      romanji: "ya",
      hiragana: "や",
      katakana: "ヤ",
      pronunciation: "[ja]",
      base: ["a", "y", "ya"],
      similarKatakana: ["ma", "a"],
      digraph: true,
      frequency: 0.0637982815448,
    },
    {
      romanji: "yu",
      hiragana: "ゆ",
      katakana: "ユ",
      pronunciation: "[ju͍]",
      base: ["u", "y", "yu"],
      similarKatakana: ["ko"],
      digraph: true,
      frequency: 0.1185482102638,
    },
    {
      romanji: "yo",
      hiragana: "よ",
      katakana: "ヨ",
      pronunciation: "[jo]",
      base: ["o", "y", "yo"],
      similarHiragana: ["na", "ha", "ho", "ba", "bo", "pa", "po", "ma"],
      similarKatakana: ["yu", "ko"],
      digraph: true,
      frequency: 0.2167810062532,
    },
  ],
  [
    {
      romanji: "k",
      title: true,
    },
    {
      romanji: "ka",
      hiragana: "か",
      katakana: "カ",
      pronunciation: "[ka]",
      base: ["k", "a"],
      similarHiragana: ["ga"],
      similarKatakana: ["ku", "ke", "ta", "ga"],
      frequency: 0.150410975006,
      strokes: [2.988, 7.05],
    },
    {
      romanji: "ki",
      hiragana: "き",
      katakana: "キ",
      pronunciation: "[ki]",
      base: ["k", "i"],
      similarHiragana: ["sa", "za", "chi", "gi"],
      similarKatakana: ["gi"],
      frequency: 0.157003113542,
      strokes: [2.988, 5.6875],
    },
    {
      romanji: "ku",
      hiragana: "く",
      katakana: "ク",
      pronunciation: "[ku͍]",
      base: ["k", "u"],
      similarHiragana: ["gu"],
      similarKatakana: ["ka", "ke", "ta", "fu", "wa", "gu"],
      frequency: 0.14781457562429998,
      strokes: [2.988, 4.325],
    },
    {
      romanji: "ke",
      hiragana: "け",
      katakana: "ケ",
      pronunciation: "[ke]",
      base: ["k", "e"],
      similarHiragana: ["ha", "ge"],
      similarKatakana: ["ka", "ku", "ta", "ge"],
      frequency: 0.071878518879,
      strokes: [2.988, 2.9625],
    },
    {
      romanji: "ko",
      hiragana: "こ",
      katakana: "コ",
      pronunciation: "[ko]",
      base: ["k", "o"],
      similarHiragana: ["ni", "go", "ta"],
      similarKatakana: ["yu", "go"],
      frequency: 0.102204670007,
      strokes: [2.988, 1.6],
    },
    {
      romanji: "kya",
      hiragana: "きゃ",
      katakana: "キャ",
      pronunciation: "[kʲa]",
      base: ["k", "ki", "ya"],
      digraph: true,
    },
    {
      romanji: "kyu",
      hiragana: "きゅ",
      katakana: "キュ",
      pronunciation: "[kʲu͍]",
      base: ["k", "ki", "yu"],
      digraph: true,
    },
    {
      romanji: "kyo",
      hiragana: "きょ",
      katakana: "キョ",
      pronunciation: "[kʲo]",
      base: ["k", "ki", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "g",
      title: true,
      diacritic: true,
    },
    {
      romanji: "ga",
      hiragana: "が",
      katakana: "ガ",
      pronunciation: "[ɡa]",
      base: ["g", "a"],
      similarHiragana: ["ka"],
      similarKatakana: ["ka", "gu", "da"],
      frequency: 0.0849979006587,
    },
    {
      romanji: "gi",
      hiragana: "ぎ",
      katakana: "ギ",
      pronunciation: "[ɡi]",
      base: ["g", "i"],
      similarHiragana: ["sa", "za", "chi", "ki"],
      similarKatakana: ["ki"],
      frequency: 0.0437376002212,
    },
    {
      romanji: "gu",
      hiragana: "ぐ",
      katakana: "グ",
      pronunciation: "[ɡu͍]",
      base: ["g", "u"],
      similarHiragana: ["ku"],
      similarKatakana: ["ku", "ge", "ga", "da", "bu"],
      frequency: 0.00993168037071,
    },
    {
      romanji: "ge",
      hiragana: "げ",
      katakana: "ゲ",
      pronunciation: "[ɡe]",
      base: ["g", "e"],
      similarHiragana: ["ba", "ke"],
      similarKatakana: ["ke", "gu"],
      frequency: 0.0345274202833,
    },
    {
      romanji: "go",
      hiragana: "ご",
      katakana: "ゴ",
      pronunciation: "[ɡo]",
      base: ["g", "o"],
      similarHiragana: ["ni", "ko", "da"],
      similarKatakana: ["ko"],
      frequency: 0.0554720210089,
    },
    {
      romanji: "gya",
      hiragana: "ぎゃ",
      katakana: "ギャ",
      pronunciation: "[ɡʲa]",
      base: ["g", "gi", "ya"],
      digraph: true,
    },
    {
      romanji: "gyu",
      hiragana: "ぎゅ",
      katakana: "ギュ",
      pronunciation: "[ɡʲu͍]",
      base: ["g", "gi", "yu"],
      digraph: true,
    },
    {
      romanji: "gyo",
      hiragana: "ぎょ",
      katakana: "ギョ",
      pronunciation: "[ɡʲo]",
      base: ["g", "gi", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "s",
      title: true,
      noTranscription: true,
    },
    {
      romanji: "sa",
      hiragana: "さ",
      katakana: "サ",
      pronunciation: "[sa]",
      base: ["s", "a"],
      similarHiragana: ["za", "chi", "ki", "gi"],
      similarKatakana: ["za"],
      frequency: 0.0979804489832,
      strokes: [4.076, 7.05],
    },
    {
      romanji: "shi",
      hiragana: "し",
      katakana: "シ",
      pronunciation: "[ɕi]",
      exception: true,
      base: ["s", "i"],
      similarHiragana: ["ji"],
      similarKatakana: ["ji", "so", "tsu", "n", "no", "zo"],
      frequency: 0.188668325613,
      strokes: [4.076, 5.6875],
    },
    {
      romanji: "su",
      hiragana: "す",
      katakana: "ス",
      pronunciation: "[su͍]",
      base: ["s", "u"],
      similarHiragana: ["zu"],
      similarKatakana: ["zu", "nu", "fu"],
      frequency: 0.074406992057,
      strokes: [4.076, 4.325],
    },
    {
      romanji: "se",
      hiragana: "せ",
      katakana: "セ",
      pronunciation: "[se]",
      base: ["s", "e"],
      similarHiragana: ["ze"],
      similarKatakana: ["ze"],
      frequency: 0.0865337343492,
      strokes: [4.076, 2.9625],
    },
    {
      romanji: "so",
      hiragana: "そ",
      katakana: "ソ",
      pronunciation: "[so]",
      base: ["s", "o"],
      similarHiragana: ["zo"],
      similarKatakana: ["zo", "shi", "tsu", "n", "no", "me"],
      frequency: 0.0397545701157,
      strokes: [4.076, 1.6],
    },
    {
      romanji: "sha",
      hiragana: "しゃ",
      katakana: "シャ",
      pronunciation: "[ɕa]",
      exception: true,
      base: ["s", "shi", "ya"],
      digraph: true,
    },
    {
      romanji: "shu",
      hiragana: "しゅ",
      katakana: "シュ",
      pronunciation: "[ɕu͍]",
      exception: true,
      base: ["s", "shi", "yu"],
      digraph: true,
    },
    {
      romanji: "sho",
      hiragana: "しょ",
      katakana: "ショ",
      pronunciation: "[ɕo]",
      exception: true,
      base: ["s", "shi", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "s",
      title: true,
      transcription: true
    },
    {
      romanji: "sa",
      hiragana: "さ",
      katakana: "サ",
      pronunciation: "[sa]",
      base: ["s", "a"],
      similarHiragana: ["za", "chi", "ki", "gi"],
      similarKatakana: ["za"],
      frequency: 0.0979804489832,
      strokes: [4.076, 7.05],
    },
    {
      romanji: "si",
      katakana: "サィ",
      pronunciation: "[si]",
      base: ["s", "sa", "i"],
      foreign: true,
    },
    {
      romanji: "su",
      hiragana: "す",
      katakana: "ス",
      pronunciation: "[su͍]",
      base: ["s", "u"],
      similarHiragana: ["zu"],
      similarKatakana: ["zu", "nu", "fu"],
      frequency: 0.074406992057,
      strokes: [4.076, 4.325],
    },
    {
      romanji: "se",
      hiragana: "せ",
      katakana: "セ",
      pronunciation: "[se]",
      base: ["s", "e"],
      similarHiragana: ["ze"],
      similarKatakana: ["ze"],
      frequency: 0.0865337343492,
      strokes: [4.076, 2.9625],
    },
    {
      romanji: "so",
      hiragana: "そ",
      katakana: "ソ",
      pronunciation: "[so]",
      base: ["s", "o"],
      similarHiragana: ["zo"],
      similarKatakana: ["zo", "shi", "tsu", "n", "no", "me"],
      frequency: 0.0397545701157,
      strokes: [4.076, 1.6],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "sh",
      title: true,
      transcription: true,
    },
    {
      romanji: "sha",
      hiragana: "しゃ",
      katakana: "シャ",
      pronunciation: "[ɕa]",
      base: ["sh", "shi", "ya", "a"],
    },
    {
      romanji: "shi",
      hiragana: "し",
      katakana: "シ",
      pronunciation: "[ɕi]",
      base: ["sh", "i"],
      similarHiragana: ["ji"],
      similarKatakana: ["ji", "so", "tsu", "n", "no", "zo"],
    },
    {
      romanji: "shu",
      hiragana: "しゅ",
      katakana: "シュ",
      pronunciation: "[ɕu͍]",
      base: ["sh", "shi", "yu", "u"],
    },
    {
      romanji: "she",
      katakana: "シェ",
      pronunciation: "[ɕe]",
      base: ["sh", "shi", "e"],
      foreign: true,
    },
    {
      romanji: "sho",
      hiragana: "しょ",
      katakana: "ショ",
      pronunciation: "[ɕo]",
      base: ["sh", "shi", "yo", "o"],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "z",
      title: true,
      diacritic: true,
      noTranscription: true,
    },
    {
      romanji: "za",
      hiragana: "ざ",
      katakana: "ザ",
      pronunciation: "[za]",
      base: ["z", "a"],
      similarHiragana: ["sa", "chi", "ki", "gi"],
      similarKatakana: ["sa"],
      frequency: 0.0183592238036,
    },
    {
      romanji: "ji",
      hiragana: "じ",
      katakana: "ジ",
      pronunciation: "[d͡ʑi]",
      exception: true,
      base: ["z", "i"],
      similarHiragana: ["shi"],
      similarKatakana: ["shi", "zo", "tsu"],
      frequency: 0.0854006405609,
    },
    {
      romanji: "zu",
      hiragana: "ず",
      katakana: "ズ",
      pronunciation: "[zu͍]",
      base: ["z", "u"],
      similarHiragana: ["su"],
      similarKatakana: ["su"],
      frequency: 0.0109785598187,
    },
    {
      romanji: "ze",
      hiragana: "ぜ",
      katakana: "ゼ",
      pronunciation: "[ze]",
      base: ["z", "e"],
      similarHiragana: ["se"],
      similarKatakana: ["se"],
      frequency: 0.0671601359949,
    },
    {
      romanji: "zo",
      hiragana: "ぞ",
      katakana: "ゾ",
      pronunciation: "[zo]",
      base: ["z", "o"],
      similarHiragana: ["so"],
      similarKatakana: ["so"],
      frequency: 0.015282670633,
    },
    {
      romanji: "ja",
      hiragana: "じゃ",
      katakana: "ジャ",
      pronunciation: "[d͡ʑa]",
      exception: true,
      base: ["z", "ji", "ya"],
      digraph: true,
    },
    {
      romanji: "ju",
      hiragana: "じゅ",
      katakana: "ジュ",
      pronunciation: "[d͡ʑu͍]",
      exception: true,
      base: ["z", "ji", "yu"],
      digraph: true,
    },
    {
      romanji: "jo",
      hiragana: "じょ",
      katakana: "ジョ",
      pronunciation: "[d͡ʑo]",
      exception: true,
      base: ["z", "ji", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "z",
      title: true,
      diacritic: true,
      transcription: true,
    },
    {
      romanji: "za",
      hiragana: "ざ",
      katakana: "ザ",
      pronunciation: "[za]",
      base: ["z", "a"],
      similarHiragana: ["sa", "chi", "ki", "gi"],
      similarKatakana: ["sa"],
      frequency: 0.0183592238036,
    },
    {
      romanji: "zi",
      katakana: "ザィ",
      pronunciation: "[zi]",
      foreign: true,
      base: ["z", "za", "i"],
    },
    {
      romanji: "zu",
      hiragana: "ず",
      katakana: "ズ",
      pronunciation: "[zu͍]",
      base: ["z", "u"],
      similarHiragana: ["su"],
      similarKatakana: ["su"],
      frequency: 0.0109785598187,
    },
    {
      romanji: "ze",
      hiragana: "ぜ",
      katakana: "ゼ",
      pronunciation: "[ze]",
      base: ["z", "e"],
      similarHiragana: ["se"],
      similarKatakana: ["se"],
      frequency: 0.0671601359949,
    },
    {
      romanji: "zo",
      hiragana: "ぞ",
      katakana: "ゾ",
      pronunciation: "[zo]",
      base: ["z", "o"],
      similarHiragana: ["so"],
      similarKatakana: ["so"],
      frequency: 0.015282670633,
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "j",
      title: true,
      diacritic: true,
      transcription: true,
    },
    {
      romanji: "ja",
      hiragana: "じゃ",
      katakana: "ジャ",
      pronunciation: "[d͡ʑa]",
      exception: true,
      base: ["ji", "ya", "j", "a"],
    },
    {
      romanji: "ji",
      hiragana: "じ",
      katakana: "ジ",
      pronunciation: "[d͡ʑi]",
      exception: true,
      base: ["j", "i"],
      similarHiragana: ["shi"],
      similarKatakana: ["shi", "zo", "tsu"],
      frequency: 0.0854006405609,
    },
    {
      romanji: "ju",
      hiragana: "じゅ",
      katakana: "ジュ",
      pronunciation: "[d͡ʑu͍]",
      exception: true,
      base: ["ji", "yu", "j", "u"],
    },
    {
      romanji: "je",
      katakana: "ジェ",
      pronunciation: "[d͡ʑe]",
      base: ["ji", "e", "j", "e"],
      foreign: true,
    },
    {
      romanji: "jo",
      hiragana: "じょ",
      katakana: "ジョ",
      pronunciation: "[d͡ʑo]",
      exception: true,
      base: ["ji", "yo", "j", "o"],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "t",
      title: true,
      noTranscription: true,
    },
    {
      romanji: "ta",
      hiragana: "た",
      katakana: "タ",
      pronunciation: "[ta]",
      similarHiragana: ["da", "ko", "ni"],
      similarKatakana: ["da", "ka", "ku", "ke", "nu"],
      base: ["t", "a"],
      frequency: 0.113535819388,
      strokes: [5.164, 7.05],
    },
    {
      romanji: "chi",
      hiragana: "ち",
      katakana: "チ",
      pronunciation: "[ t͡ɕi]",
      exception: true,
      base: ["t", "i"],
      similarHiragana: ["di", "sa", "za", "ki", "gi", "ra"],
      frequency: 0.137902402959,
      strokes: [5.164, 5.6875],
    },
    {
      romanji: "tsu",
      hiragana: "つ",
      katakana: "ツ",
      pronunciation: "[ t͡su͍]",
      exception: true,
      base: ["t", "u"],
      similarHiragana: ["du"],
      similarKatakana: ["shi", "ji", "so", "zo", "no", "n"],
      frequency: 0.16964530423302,
      strokes: [5.164, 4.325],
    },
    {
      romanji: "te",
      hiragana: "て",
      katakana: "テ",
      pronunciation: "[te]",
      base: ["t", "e"],
      similarHiragana: ["de"],
      similarKatakana: ["de"],
      frequency: 0.0999492063647,
      strokes: [5.164, 2.9625],
    },
    {
      romanji: "to",
      hiragana: "と",
      katakana: "ト",
      pronunciation: "[to]",
      base: ["t", "o"],
      similarHiragana: ["do"],
      similarKatakana: ["do"],
      frequency: 0.1524276116383,
      strokes: [5.164, 1.6],
    },
    {
      romanji: "cha",
      hiragana: "ちゃ",
      katakana: "チャ",
      pronunciation: "[ t͡ɕa]",
      exception: true,
      base: ["chi", "ya", "t"],
      digraph: true,
    },
    {
      romanji: "chu",
      hiragana: "ちゅ",
      katakana: "チュ",
      pronunciation: "[ t͡ɕu͍]",
      exception: true,
      base: ["chi", "yu", "t"],
      digraph: true,
    },
    {
      romanji: "cho",
      hiragana: "ちょ",
      katakana: "チョ",
      pronunciation: "[ t͡ɕo]",
      exception: true,
      base: ["chi", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "t",
      title: true,
      transcription: true,
    },
    {
      romanji: "ta",
      hiragana: "た",
      katakana: "タ",
      pronunciation: "[ta]",
      similarHiragana: ["da", "ko", "ni"],
      similarKatakana: ["da", "ka", "ku", "ke", "nu"],
      base: ["t", "a"],
      frequency: 0.113535819388,
      strokes: [5.164, 7.05],
    },
    {
      romanji: "ti",
      katakana: "ティ",
      pronunciation: "[ti]",
      base: ["te", "i", "t"],
      foreign: true,
    },
    {
      romanji: "tu",
      katakana: "トゥ",
      pronunciation: "[tu͍]",
      base: ["to", "u", "t"],
      foreign: true,
    },
    {
      romanji: "te",
      hiragana: "て",
      katakana: "テ",
      pronunciation: "[te]",
      base: ["t", "e"],
      similarHiragana: ["de"],
      similarKatakana: ["de"],
      frequency: 0.0999492063647,
      strokes: [5.164, 2.9625],
    },
    {
      romanji: "to",
      hiragana: "と",
      katakana: "ト",
      pronunciation: "[to]",
      base: ["t", "o"],
      similarHiragana: ["do"],
      similarKatakana: ["do"],
      frequency: 0.1524276116383,
      strokes: [5.164, 1.6],
    },
    {digraph: true},
    {
      romanji: "tyu",
      katakana: "テュ",
      pronunciation: "[tʲu͍]",
      base: ["te", "yu", "t"],
      digraph: true,
      foreign: true,
    },
    {digraph: true},
  ],
  [
    {
      romanji: "ch",
      title: true,
      transcription: true,
    },
    {
      romanji: "cha",
      hiragana: "ちゃ",
      katakana: "チャ",
      pronunciation: "[t͡ɕa]",
      base: ["chi", "ya", "ch", "a"],
    },
    {
      romanji: "chi",
      hiragana: "ち",
      katakana: "チ",
      pronunciation: "[t͡ɕi]",
      base: ["ch", "i"],
      similarHiragana: ["sa", "za", "ki", "gi", "ra", "di"],
      frequency: 0.137902402959,
      strokes: [5.164, 5.6875],
    },
    {
      romanji: "chu",
      hiragana: "ちゅ",
      katakana: "チュ",
      pronunciation: "[t͡ɕu͍]",
      base: ["chi", "yu", "ch", "u"],
    },
    {
      romanji: "che",
      katakana: "チェ",
      pronunciation: "[t͡ɕe]",
      base: ["chi", "e", "ch"],
      foreign: true,
    },
    {
      romanji: "cho",
      hiragana: "ちょ",
      katakana: "チョ",
      pronunciation: "[t͡ɕo]",
      base: ["chi", "yo", "ch", "o"],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "ts",
      title: true,
      transcription: true,
    },
    {
      romanji: "tsa",
      katakana: "ツァ",
      pronunciation: "[t͡sa]",
      base: ["tsu", "a", "ts"],
      foreign: true,
    },
    {
      romanji: "tsi",
      katakana: "ツィ",
      pronunciation: "[t͡si]",
      base: ["tsu", "i", "ts"],
      foreign: true,
    },
    {
      romanji: "tsu",
      hiragana: "つ",
      katakana: "ツ",
      pronunciation: "[t͡su͍]",
      base: ["ts", "u", "ts"],
      similarHiragana: ["du"],
      similarKatakana: ["shi", "ji", "so", "zo", "no", "n"],
      frequency: 0.16964530423302,
      strokes: [5.164, 4.325],
    },
    {
      romanji: "tse",
      katakana: "ツェ",
      pronunciation: "[t͡se]",
      base: ["tsu", "e", "ts"],
      foreign: true,
    },
    {
      romanji: "tso",
      katakana: "ツォ",
      pronunciation: "[t͡so]",
      base: ["tsu", "o", "ts"],
      foreign: true,
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "d",
      title: true,
      diacritic: true,
      noTranscription: true,
    },
    {
      romanji: "da",
      hiragana: "だ",
      katakana: "ダ",
      pronunciation: "[da]",
      base: ["d", "a"],
      similarHiragana: ["ta", "go", "ni"],
      similarKatakana: ["ta", "ga", "gu"],
      frequency: 0.0534855728586,
    },
    {
      romanji: "di",
      hiragana: "ぢ",
      katakana: "ディ",
      pronunciation: "[di]",
      base: ["d", "i"],
      similarHiragana: ["chi"],
      foreign: true,
    },
    {
      romanji: "du",
      hiragana: "づ",
      katakana: "ドゥ",
      pronunciation: "[du͍]",
      base: ["d", "u"],
      similarHiragana: ["tsu"],
      frequency: 0.00892347545926,
      foreign: true,
    },
    {
      romanji: "de",
      hiragana: "で",
      katakana: "デ",
      pronunciation: "[de]",
      base: ["d", "e"],
      similarHiragana: ["te"],
      similarKatakana: ["te"],
      frequency: 0.0648559195296,
    },
    {
      romanji: "do",
      hiragana: "ど",
      katakana: "ド",
      pronunciation: "[do]",
      base: ["d", "o"],
      similarHiragana: ["to"],
      similarKatakana: ["to"],
      frequency: 0.0803261863835
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "d",
      title: true,
      diacritic: true,
      transcription: true,
    },
    {
      romanji: "da",
      hiragana: "だ",
      katakana: "ダ",
      pronunciation: "[da]",
      base: ["d", "a"],
      similarHiragana: ["ta", "go", "ni"],
      similarKatakana: ["ta", "ga", "gu"],
      frequency: 0.0534855728586,
    },
    {
      romanji: "di",
      hiragana: "ぢ",
      katakana: "ディ",
      pronunciation: "[di]",
      base: ["de", "i", "d"],
      similarHiragana: ["chi"],
      foreign: true,
    },
    {
      romanji: "du",
      hiragana: "づ",
      katakana: "ドゥ",
      pronunciation: "[du͍]",
      base: ["do", "u", "d"],
      similarHiragana: ["tsu"],
      foreign: true,
      frequency: 0.00892347545926,
    },
    {
      romanji: "de",
      hiragana: "で",
      katakana: "デ",
      pronunciation: "[de]",
      base: ["d", "e"],
      similarHiragana: ["te"],
      similarKatakana: ["te"],
      frequency: 0.0648559195296,
    },
    {
      romanji: "do",
      hiragana: "ど",
      katakana: "ド",
      pronunciation: "[do]",
      base: ["d", "o"],
      similarHiragana: ["to"],
      similarKatakana: ["to"],
      frequency: 0.0803261863835,
    },
    {digraph: true},
    {
      romanji: "dyu",
      katakana: "デュ",
      pronunciation: "[dʲu͍]",
      base: ["de", "yu", "d"],
      digraph: true,
      foreign: true,
    },
    {digraph: true},
  ],
  [
    {
      romanji: "n",
      hiragana: "ん",
      katakana: "ン",
      pronunciation: "[n|m|ŋ]",
      similarKatakana: ["so", "tsu", "shi", "no", "me"],
      frequency: 0.266529757302,
      strokes: [12.78, 7.05],
    },
    {
      romanji: "na",
      hiragana: "な",
      katakana: "ナ",
      pronunciation: "[na]",
      base: ["n", "a"],
      similarHiragana: ["ha", "ho", "ba", "bo", "pa", "po", "ma", "yo"],
      frequency: 0.0930059284131,
      strokes: [6.252, 7.05],
    },
    {
      romanji: "ni",
      hiragana: "に",
      katakana: "ニ",
      pronunciation: "[ni]",
      base: ["n", "i"],
      similarHiragana: ["ko", "go", "ta"],
      frequency: 0.152149857877,
      strokes: [6.252, 5.6875],
    },
    {
      romanji: "nu",
      hiragana: "ぬ",
      katakana: "ヌ",
      pronunciation: "[nu͍]",
      base: ["n", "u"],
      similarHiragana: ["ne", "no", "me"],
      similarKatakana: ["ta", "fu", "wo", "su"],
      frequency: 0,
      strokes: [6.252, 4.325],
    },
    {
      romanji: "ne",
      hiragana: "ね",
      katakana: "ネ",
      pronunciation: "[ne]",
      base: ["n", "e"],
      similarHiragana: ["nu", "re", "wa"],
      frequency: 0.036194621743,
      strokes: [6.252, 2.9625],
    },
    {
      romanji: "no",
      hiragana: "の",
      katakana: "ノ",
      pronunciation: "[no]",
      similarHiragana: ["nu", "me"],
      similarKatakana: ["shi", "so", "tsu", "n", "me"],
      base: ["n", "o"],
      frequency: 0.140954091958,
      strokes: [6.252, 1.6],
    },
    {
      romanji: "nya",
      hiragana: "にゃ",
      katakana: "ニャ",
      pronunciation: "[nʲa]",
      base: ["n", "ni", "ya"],
      digraph: true,
    },
    {
      romanji: "nyu",
      hiragana: "にゅ",
      katakana: "ニュ",
      pronunciation: "[nʲu͍]",
      base: ["n", "ni", "yu"],
      digraph: true,
    },
    {
      romanji: "nyo",
      hiragana: "にょ",
      katakana: "ニョ",
      pronunciation: "[nʲo]",
      base: ["n", "ni", "yo"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "h",
      title: true,
      noTranscription: true,
    },
    {
      romanji: "ha",
      hiragana: "は",
      katakana: "ハ",
      pronunciation: "[ha]",
      base: ["h", "a"],
      similarHiragana: ["ba", "pa", "na", "ho", "bo", "po", "ma", "yo"],
      similarKatakana: ["ba", "pa"],
      frequency: 0.118262517001,
      strokes: [7.34, 7.05],
    },
    {
      romanji: "hi",
      hiragana: "ひ",
      katakana: "ヒ",
      pronunciation: "[çi]",
      base: ["h", "i"],
      similarHiragana: ["bi", "pi"],
      similarKatakana: ["bi", "pi"],
      frequency: 0.0434631618981,
      strokes: [7.34, 5.6875],
    },
    {
      romanji: "fu",
      hiragana: "ふ",
      katakana: "フ",
      pronunciation: "[ɸu͍]",
      exception: true,
      base: ["h", "u"],
      similarHiragana: ["bu", "pu"],
      similarKatakana: ["bu", "pu", "wo", "wa", "ra", "ku"],
      frequency: 0.0462202484862,
      strokes: [7.34, 4.325],
    },
    {
      romanji: "he",
      hiragana: "へ",
      katakana: "ヘ",
      pronunciation: "[he]",
      base: ["h", "e"],
      similarHiragana: ["be", "pe"],
      similarKatakana: ["be", "pe"],
      frequency: 0.0160041004697,
      strokes: [7.34, 2.9625],
    },
    {
      romanji: "ho",
      hiragana: "ほ",
      katakana: "ホ",
      pronunciation: "[ho]",
      base: ["h", "o"],
      similarHiragana: ["ba", "pa", "na", "ha", "bo", "po", "ma", "yo"],
      similarKatakana: ["bo", "po"],
      frequency: 0.0399934724261,
      strokes: [7.34, 1.6],
    },
    {
      romanji: "hya",
      hiragana: "ひゃ",
      katakana: "ヒャ",
      pronunciation: "[ça]",
      base: ["hi", "ya", "h"],
      digraph: true,
    },
    {
      romanji: "hyu",
      hiragana: "ひゅ",
      katakana: "ヒュ",
      pronunciation: "[çu͍]",
      base: ["hi", "yu", "h"],
      digraph: true,
    },
    {
      romanji: "hyo",
      hiragana: "ひょ",
      katakana: "ヒョ",
      pronunciation: "[ço]",
      base: ["hi", "yo", "h"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "h",
      title: true,
      transcription: true,
    },
    {
      romanji: "ha",
      hiragana: "は",
      katakana: "ハ",
      pronunciation: "[ha]",
      base: ["h", "a"],
      similarHiragana: ["ba", "pa", "na", "ho", "bo", "po", "ma", "yo"],
      similarKatakana: ["ba", "pa"],
      frequency: 0.118262517001,
      strokes: [7.34, 7.05],
    },
    {
      romanji: "hi",
      hiragana: "ひ",
      katakana: "ヒ",
      pronunciation: "[çi]",
      base: ["h", "i"],
      similarHiragana: ["bi", "pi"],
      similarKatakana: ["bi", "pi"],
      frequency: 0.0434631618981,
      strokes: [7.34, 5.6875],
    },
    {
      romanji: "hu",
      katakana: "ホゥ",
      pronunciation: "[hu͍]",
      exception: true,
      base: ["ho", "u", "h"],
      foreign: true,
    },
    {
      romanji: "he",
      hiragana: "へ",
      katakana: "ヘ",
      pronunciation: "[he]",
      base: ["h", "e"],
      similarHiragana: ["be", "pe"],
      similarKatakana: ["be", "pe"],
      frequency: 0.0160041004697,
      strokes: [7.34, 2.9625],
    },
    {
      romanji: "ho",
      hiragana: "ほ",
      katakana: "ホ",
      pronunciation: "[ho]",
      base: ["h", "o"],
      similarHiragana: ["bo", "po", "na", "ha", "ba", "pa", "ma", "yo"],
      similarKatakana: ["bo", "po"],
      frequency: 0.0399934724261,
      strokes: [7.34, 1.6],
    },
    {
      romanji: "hya",
      hiragana: "ひゃ",
      katakana: "ヒャ",
      pronunciation: "[ça]",
      base: ["hi", "ya", "h"],
      digraph: true,
    },
    {
      romanji: "hyu",
      hiragana: "ひゅ",
      katakana: "ヒュ",
      pronunciation: "[çu͍]",
      base: ["hi", "yu", "h"],
      digraph: true,
    },
    {
      romanji: "hyo",
      hiragana: "ひょ",
      katakana: "ヒョ",
      pronunciation: "[ço]",
      base: ["hi", "yo", "h"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "f",
      title: true,
      transcription: true,
    },
    {
      romanji: "fa",
      katakana: "ファ",
      pronunciation: "[ɸa]",
      base: ["fu", "a", "f"],
      foreign: true,
    },
    {
      romanji: "fi",
      katakana: "フィ",
      pronunciation: "[ɸi]",
      base: ["fu", "i", "f"],
      foreign: true,
    },
    {
      romanji: "fu",
      hiragana: "ふ",
      katakana: "フ",
      pronunciation: "[ɸu͍]",
      base: ["f", "u"],
      similarHiragana: ["bu", "pu"],
      similarKatakana: ["bu", "pu", "wo", "wa", "ra", "ku"],
      frequency: 0.0462202484862,
      strokes: [7.34, 4.325],
    },
    {
      romanji: "fe",
      katakana: "フェ",
      pronunciation: "[ɸe]",
      base: ["fu", "e", "f"],
      foreign: true,
    },
    {
      romanji: "fo",
      katakana: "フォ",
      pronunciation: "[ɸo]",
      base: ["fu", "o", "f"],
      foreign: true,
    },
    {
      romanji: "fya",
      katakana: "フャ",
      pronunciation: "[ɸʲa]",
      base: ["fu", "ya", "f"],
      digraph: true,
      foreign: true,
    },
    {
      romanji: "fyu",
      katakana: "フュ",
      pronunciation: "[ɸʲu͍]",
      base: ["fu", "yu", "f"],
      digraph: true,
      foreign: true,
    },
    {
      romanji: "fyo",
      katakana: "フョ",
      pronunciation: "[ɸʲo]",
      base: ["fu", "yo", "f"],
      digraph: true,
      foreign: true,
    },
  ],
  [
    {
      romanji: "b",
      title: true,
      diacritic: true,
      frequency: 0,
    },
    {
      romanji: "ba",
      hiragana: "ば",
      katakana: "バ",
      pronunciation: "[ba]",
      base: ["b", "a"],
      similarHiragana: ["ha", "pa", "na", "ho", "bo", "po", "ma", "yo"],
      similarKatakana: ["ha", "pa"],
      frequency: 0.0233712764971,
    },
    {
      romanji: "bi",
      hiragana: "び",
      katakana: "ビ",
      pronunciation: "[bi]",
      base: ["b", "i"],
      similarHiragana: ["hi", "pi"],
      similarKatakana: ["hi", "pi"],
      frequency: 0.0179541345926,
    },
    {
      romanji: "bu",
      hiragana: "ぶ",
      katakana: "ブ",
      pronunciation: "[bu͍]",
      base: ["b", "u"],
      similarHiragana: ["fu", "pu"],
      similarKatakana: ["fu", "pu", "zu", "gu"],
      frequency: 0.0332831982086,
    },
    {
      romanji: "be",
      hiragana: "べ",
      katakana: "ベ",
      pronunciation: "[be]",
      base: ["b", "e"],
      similarHiragana: ["he", "pe"],
      similarKatakana: ["he", "pe"],
      frequency: 0.0189407554386,
    },
    {
      romanji: "bo",
      hiragana: "ぼ",
      katakana: "ベ",
      pronunciation: "[bo]",
      base: ["b", "o"],
      similarHiragana: ["ho", "po", "na", "ha", "ba", "pa", "ma", "yo"],
      similarKatakana: ["ho", "po"],
      frequency: 0.0138167166406,
    },
    {
      romanji: "bya",
      hiragana: "びゃ",
      katakana: "ビャ",
      pronunciation: "[bʲa]",
      base: ["bi", "ya", "b"],
      digraph: true,
    },
    {
      romanji: "byu",
      hiragana: "びゅ",
      katakana: "ビュ",
      pronunciation: "[bʲu͍]",
      base: ["bi", "yu", "b"],
      digraph: true,
    },
    {
      romanji: "byo",
      hiragana: "びょ",
      katakana: "ビョ",
      pronunciation: "[bʲo]",
      base: ["bi", "yo", "b"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "p",
      title: true,
      diacritic: true,
    },
    {
      romanji: "pa",
      hiragana: "ぱ",
      katakana: "パ",
      pronunciation: "[pa]",
      base: ["p", "a"],
      similarHiragana: ["ha", "ba", "na", "ho", "bo", "po", "ma", "yo"],
      similarKatakana: ["ha", "ba"],
      frequency: 0.0230953311259,
    },
    {
      romanji: "pi",
      hiragana: "ぴ",
      katakana: "ピ",
      pronunciation: "[pi]",
      base: ["p", "i"],
      similarHiragana: ["hi", "bi"],
      similarKatakana: ["hi", "bi"],
      frequency: 0.00748959504987,
    },
    {
      romanji: "pu",
      hiragana: "ぷ",
      katakana: "プ",
      pronunciation: "[pu͍]",
      base: ["p", "u"],
      similarHiragana: ["fu", "bu"],
      similarKatakana: ["fu", "bu"],
      frequency: 0,
    },
    {
      romanji: "pe",
      hiragana: "ぺ",
      katakana: "ペ",
      pronunciation: "[pe]",
      base: ["p", "e"],
      similarHiragana: ["he", "be"],
      similarKatakana: ["he", "be"],
      frequency: 0,
    },
    {
      romanji: "po",
      hiragana: "ぽ",
      katakana: "ポ",
      pronunciation: "[po]",
      base: ["p", "o"],
      similarHiragana: ["ho", "bo", "na", "ha", "ba", "pa", "ma", "yo"],
      similarKatakana: ["ho", "bo"],
      frequency: 0.015710207896,
    },
    {
      romanji: "pya",
      hiragana: "ぴゃ",
      katakana: "ピャ",
      pronunciation: "[pʲa]",
      base: ["pi", "ya", "p"],
      digraph: true,
    },
    {
      romanji: "pyu",
      hiragana: "ぴゅ",
      katakana: "ピュ",
      pronunciation: "[pʲu͍]",
      base: ["pi", "yu", "p"],
      digraph: true,
    },
    {
      romanji: "pyo",
      hiragana: "ぴょ",
      katakana: "ピョ",
      pronunciation: "[pʲo]",
      base: ["pi", "yo", "p"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "m",
      title: true,
    },
    {
      romanji: "ma",
      hiragana: "ま",
      katakana: "マ",
      pronunciation: "[ma]",
      base: ["m", "a"],
      similarHiragana: ["na", "ha", "ho", "ba", "bo", "pa", "po", "yo"],
      similarKatakana: ["a", "ya", "mu"],
      frequency: 0.0492665500398,
      strokes: [8.428, 7.05],
    },
    {
      romanji: "mi",
      hiragana: "み",
      katakana: "ミ",
      pronunciation: "[mi]",
      base: ["m", "i"],
      frequency: 0.0399016361983,
      strokes: [8.428, 5.6875],
    },
    {
      romanji: "mu",
      hiragana: "む",
      katakana: "ム",
      pronunciation: "[mu͍]",
      base: ["m", "u"],
      similarKatakana: ["ma"],
      frequency: 0.0183592238036,
      strokes: [8.428, 4.325],
    },
    {
      romanji: "me",
      hiragana: "め",
      katakana: "メ",
      pronunciation: "[me]",
      similarHiragana: ["no", "nu"],
      similarKatakana: ["so", "n", "no"],
      base: ["m", "e"],
      frequency: 0.0498916585603,
      strokes: [8.428, 2.9625],
    },
    {
      romanji: "mo",
      hiragana: "も",
      katakana: "モ",
      pronunciation: "[mo]",
      base: ["m", "o"],
      frequency: 0.0535751111188,
      strokes: [8.428, 1.6],
    },
    {
      romanji: "mya",
      hiragana: "みゃ",
      katakana: "ミャ",
      pronunciation: "[mʲa]",
      base: ["mi", "ya", "m"],
      digraph: true,
    },
    {
      romanji: "myu",
      hiragana: "みゅ",
      katakana: "ミュ",
      pronunciation: "[mʲu͍]",
      base: ["mi", "yu", "m"],
      digraph: true,
    },
    {
      romanji: "myo",
      hiragana: "みょ",
      katakana: "ミョ",
      pronunciation: "[mʲo]",
      base: ["mi", "yo", "m"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "y",
      title: true,
      "hideIfDigraph": true,
      noTranscription: true,
    },
    {
      romanji: "ya",
      hiragana: "や",
      katakana: "ヤ",
      pronunciation: "[ja]",
      base: ["a", "y", "ya"],
      similarKatakana: ["a", "ma"],
      frequency: 0.0637982815448,
      strokes: [9.516, 7.05],
    },
    {},
    {
      romanji: "yu",
      hiragana: "ゆ",
      katakana: "ユ",
      pronunciation: "[ju͍]",
      base: ["u", "y", "yu"],
      similarKatakana: ["ko"],
      frequency: 0.1185482102638,
      strokes: [9.516, 4.325],
    },
    {},
    {
      romanji: "yo",
      hiragana: "よ",
      katakana: "ヨ",
      pronunciation: "[jo]",
      base: ["o", "y", "yo"],
      similarHiragana: ["na", "ha", "ho", "ba", "bo", "pa", "po", "ma"],
      frequency: 0.21678100625320001,
      strokes: [9.516, 1.6],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "y",
      title: true,
      transcription: true,
    },
    {
      romanji: "ya",
      hiragana: "や",
      katakana: "ヤ",
      pronunciation: "[ja]",
      base: ["y", "a", "ya"],
      similarKatakana: ["a", "ma"],
      frequency: 0.0637982815448,
      strokes: [9.516, 7.05],
    },
    {
      romanji: "yi",
      katakana: "イィ",
      pronunciation: "[ji]",
      base: ["i", "y"],
      foreign: true,
    },
    {
      romanji: "yu",
      hiragana: "ゆ",
      katakana: "ユ",
      pronunciation: "[ju͍]",
      base: ["y", "u", "yu"],
      similarKatakana: ["ko"],
      frequency: 0.1185482102638,
      strokes: [9.516, 4.325],
    },
    {
      romanji: "ye",
      katakana: "イェ",
      pronunciation: "[je]",
      base: ["i", "e", "y"],
      foreign: true,
    },
    {
      romanji: "yo",
      hiragana: "よ",
      katakana: "ヨ",
      pronunciation: "[jo]",
      base: ["y", "o", "yo"],
      similarHiragana: ["na", "ha", "ho", "ba", "bo", "pa", "po", "ma"],
      frequency: 0.21678100625320001,
      strokes: [9.516, 1.6],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "r",
      title: true,
    },
    {
      romanji: "ra",
      hiragana: "ら",
      katakana: "ラ",
      pronunciation: "[ɽa]",
      base: ["r", "a"],
      similarHiragana: ["chi"],
      similarKatakana: ["wo", "wa", "fu"],
      frequency: 0.0712423209628,
      strokes: [10.604, 7.05],
    },
    {
      romanji: "ri",
      hiragana: "り",
      katakana: "リ",
      pronunciation: "[ɽi]",
      base: ["r", "i"],
      similarHiragana: ["i"],
      frequency: 0.0879870181803,
      strokes: [10.604, 5.6875],
    },
    {
      romanji: "ru",
      hiragana: "る",
      katakana: "ル",
      pronunciation: "[ɽu͍]",
      base: ["r", "u"],
      similarHiragana: ["ro"],
      similarKatakana: ["re"],
      frequency: 0.1054865359212,
      strokes: [10.604, 4.325],
    },
    {
      romanji: "re",
      hiragana: "れ",
      katakana: "レ",
      pronunciation: "[ɽe]",
      base: ["r", "e"],
      similarHiragana: ["ne", "wa"],
      similarKatakana: ["ru"],
      frequency: 0.05823770643416,
      strokes: [10.604, 2.9625],
    },
    {
      romanji: "ro",
      hiragana: "ろ",
      katakana: "ロ",
      pronunciation: "[ɽo]",
      base: ["r", "o"],
      similarHiragana: ["ru"],
      frequency: 0.0810294879253,
      strokes: [10.604, 1.6],
    },
    {
      romanji: "rya",
      hiragana: "りゃ",
      katakana: "リャ",
      pronunciation: "[ɽʲa]",
      base: ["ri", "ya", "r"],
      digraph: true,
    },
    {
      romanji: "ryu",
      hiragana: "りゅ",
      katakana: "リュ",
      pronunciation: "[ɽʲu͍]",
      base: ["ri", "yu", "r"],
      digraph: true,
    },
    {
      romanji: "ryo",
      hiragana: "りょ",
      katakana: "リョ",
      pronunciation: "[ɽʲo]",
      base: ["ri", "yo", "r"],
      digraph: true,
    },
  ],
  [
    {
      romanji: "w",
      title: true,
      noTranscription: true,
    },
    {
      romanji: "wa",
      hiragana: "わ",
      katakana: "ワ",
      pronunciation: "[w͍a]",
      base: ["w", "a"],
      similarHiragana: ["ne", "re"],
      similarKatakana: ["u", "wo", "ra", "fu", "vu"],
      frequency: 0.0342271354258,
      strokes: [11.692, 7.05],
    },
    {},
    {},
    {},
    {
      romanji: "wo",
      hiragana: "を",
      katakana: "ヲ",
      pronunciation: "[(w͍)o]",
      base: ["w", "o"],
      similarKatakana: ["ra", "wa", "fu"],
      frequency: 0.0716407576854,
      strokes: [11.692, 1.6],
    },
    {digraph: true},
    {digraph: true},
    {digraph: true},
  ],
  [
    {
      romanji: "w",
      title: true,
      transcription: true,
    },
    {
      romanji: "wa",
      hiragana: "わ",
      katakana: "ワ",
      pronunciation: "[w͍a]",
      base: ["w", "a"],
      similarHiragana: ["ne", "re"],
      similarKatakana: ["u", "wo", "ra", "fu", "vu"],
      frequency: 0.0342271354258,
      strokes: [11.692, 7.05],
    },
    {
      romanji: "wi",
      hiragana: "ゐ",
      katakana: "ウィ",
      pronunciation: "[wi]",
      base: ["u", "i", "w"],
      foreign: true,
    },
    {
      romanji: "wu",
      katakana: "ウゥ",
      pronunciation: "[wu͍]",
      base: ["u", "w"],
      foreign: true,
    },
    {
      romanji: "we",
      hiragana: "ゑ",
      katakana: "ウェ",
      pronunciation: "[we]",
      base: ["u", "e", "w"],
      foreign: true,
    },
    {
      romanji: "wo",
      hiragana: "を",
      katakana: "ウォ",
      pronunciation: "[wo]",
      base: ["u", "o", "w"],
      foreign: true,
    },
    {digraph: true},
    {
      romanji: "wyu",
      katakana: "ウュ",
      pronunciation: "[wʲu͍]",
      base: ["yu", "w"],
      digraph: true,
      foreign: true,
    },
    {digraph: true},
  ],
  [
    {
      romanji: "v",
      title: true,
      transcription: true,
      diacritic: true,
    },
    {
      romanji: "va",
      katakana: "ヴァ",
      pronunciation: "[va]",
      base: ["vu", "a", "v"],
      foreign: true,
    },
    {
      romanji: "vi",
      katakana: "ヴィ",
      pronunciation: "[vi]",
      base: ["vu", "i", "v"],
      foreign: true,
    },
    {
      romanji: "vu",
      katakana: "ヴ",
      pronunciation: "[vu͍]",
      base: ["u", "v"],
      similarKatakana: ["u", "wa"],
      foreign: true,
    },
    {
      romanji: "ve",
      katakana: "ヴェ",
      pronunciation: "[ve]",
      base: ["vu", "e", "v"],
      foreign: true,
    },
    {
      romanji: "vo",
      katakana: "ヴォ",
      pronunciation: "[vo]",
      base: ["vu", "o", "v"],
      foreign: true,
    },
    {
      romanji: "vya",
      katakana: "ヴャ",
      pronunciation: "[vʲa]",
      base: ["vu", "ya", "v"],
      digraph: true,
      foreign: true,
    },
    {
      romanji: "vyu",
      katakana: "ヴュ",
      pronunciation: "[vʲu͍]",
      base: ["vu", "yu", "v"],
      digraph: true,
      foreign: true,
    },
    {
      romanji: "vyo",
      katakana: "ヴョ",
      pronunciation: "[vʲo]",
      base: ["vu", "yo", "v"],
      digraph: true,
      foreign: true,
    },
  ],
];

Object.freeze(syllabary);

export default syllabary;
